version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
    depends_on: 
      - db

  db:
    image: postgres
    container_name: fastapi-challenge-db
    environment:
    - POSTGRES_DB=fastapi-challenge
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    ports:
      - 5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:

